[tool.poetry]
name = "abc-scoring-api"
version = "0.1.0"
description = ""
authors = ["m-uesaka <aleo724@gmail.com>"]
readme = "README.md"
packages = [{include = "abc_scoring_api"}]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.95.2"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pytest = "^7.3.1"
pytest-sugar = "^0.9.7"
mypy = "^1.3.0"
pylint = "^2.17.4"
hypothesis = "^6.75.3"
coverage-badge = "^1.1.0"
mkdocs-material = "^9.1.14"
mkdocstrings = "^0.21.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.messages_control]
disable = "C0330, C0326, C0114"

[tool.pylint.format]
max-line-length = 88

[tool.black]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
#  | foo.py           # also separately exclude a file named foo.py in
#                     # the root of the project
)
'''