line-length = 88

[lint]

select = ["ALL"]

# The rules we ignore
ignore = [
    "ANN1",  # missing type self and cls
    "TD001", # invalid todo tag
    "TD002", # missing todo author
    "TD003", # missing todo link
    "PD011", # pandas use of dot values
    "D100", 
    "D104",
    "D203", # one blank line before class
    "D213", # multi-line summary second line
    "COM812",
    "ISC001",
    "TRY003",
    "EM101",
    "PLR2004",
    "FA102"
]

# These rules may affect the code behavior,
# so we avoid them in usual cases.
unfixable = [
    "F401",   # imported but unused
    "F841",   # unused variable
    "F811",   # redefinition of unused variable
    "ERA001", # commented out code
]

# These rules will be applied additionally in "make format_unsafe".
# Be careful to use this command.
extend-safe-fixes = ["F401", "F841", "F811"]

[lint.per-file-ignores]
"**/tests/*" = ["D101", "D102", "D103", "S101"]