version: "3"

env:
  SRC: reflex_scoreboard/
  TEST: tests/

tasks:
  format:
    cmds:
      - rye run ruff format $SRC --config ruff.toml
      - rye run ruff format $TEST --config ruff.toml
      - rye run ruff check $SRC --fix --config ruff.toml
      - rye run ruff check $TEST --fix --config ruff.toml
  check_type:
    cmds:
      - rye run mypy $SRC
      - rye run mypy $TEST
  test:
    cmds:
      - rye run pytest $TEST --cov=$SRC --cov-branch --cov-report html:./htmlcov --cov-fail-under 80
  install:
    cmds:
      - rye sync